name: Run specs

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Run tests
        env:
          RAILS_ENV: test
          GEMFILE_RUBY_VERSION: 2.7.2
          AWS_SQS_ENDPOINT: 'http://localstack:4566'
          AWS_ACCOUNT_ID: '000000000000'
          AWS_ACCESS_KEY_ID: 'random'
          AWS_SECRET_KEY: 'random'
          AWS_SNS_CONFIGURATOR_LOGGER: true
        run: |
          bundle exec rspec
      - name: Run rubocop
        run: |
          bundle exec rubocop

